### ISSUE TITLE
Вначале хода следующего игрока статус остается

### ISSUE THREAD

**Issue by skrivopishin** [AndrewMasalski/pokerOnDices#5]
Вначале хода следующего игрока остается статус предыдущего и игрок может заблокировать уже выпавшие кости у предыдущего игрока.

**Comment by AndrewMasalski** [comment]
Гы. Чит. Пока запрещу лочить кости до первого броска.
Надо подумать, мот красивше есть вариант.

**Comment by skrivopishin** [comment]
Можно просто вначале каждого хода ролить кости, и вначале игры тоже.

**Comment by AndrewMasalski** [comment]
А вдруг всякие колдуны захотят сами решать, когда роллить кости?

**Comment by AndrewMasalski** [comment]
Fixed since v0.0.4
