### ISSUE TITLE
Каре нету в покере на костях

### ISSUE THREAD

**Issue by skrivopishin** [AndrewMasalski/pokerOnDices#7]
Вместо каре нужен квадрат

**Comment by AndrewMasalski** [comment]
https://s3-eu-west-1.amazonaws.com/mosigra.product.other/401/524/nabor_dly_pokera_v_metalli4eskoy_korobke_200_fisek_75gr.pdf
названия взяты отсюда, но при сильном желании можно и поменять

**Comment by skrivopishin** [comment]
принимается, моя ошибка

**Comment by AndrewMasalski** [comment]
Если сильно захотеть, можно вообще сделать каждому юзеру свой перевод.
Но сначала авторизацию придется сделать. А я пока не увервен, что она нужна.
